services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    depends_on:
      - db
  frontend:
    build: ./frontend
    ports:
      - "4200:80"
  db:
    image: mysql:8.0
    environment:
   
      MYSQL_DATABASE: fifa_database
      MYSQL_USER: xacademy
      MYSQL_PASSWORD: secretito123
    ports:
      - "8080:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
