version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=localhost
      - DB_USER=xacademy
      - DB_PASS=secretito
      - DB_NAME=fifa_database
    depends_on:
      - db
  frontend:
    build: ./frontend/fifa_player
    ports:
      - "4200:4200"
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: fifa_database
    ports:
      - "3306:3306"










